### ISSUE TITLE
Addition of the GPLv2 to the list?

### ISSUE THREAD

**Issue by thequbit** [DevProgress/acceptable-licenses#1]
The list explicitly calls out GPLv3.  Is there a reason v2 couldn't be added as well?

**Comment by decause** [comment]
Thanks Tim for your note.

We've based our list off of existing projects accepted to the program already, so, mostly, we just haven't had any submitted yet. As long as the project met all other requirements, I reckon project leadership would consider accepting it, and adding it to the list.

Thank you for you support, and for all your upstream contributions as a civic hacker.

**Comment by thequbit** [comment]
Got it.  Perhaps "Acceptable" rather than "Accepted" is what threw me off.  I agree any new project probably wants to be v3 anyway.  Thank you for your prompt reply.
